import React, { useState } from 'react';
import { X, Printer, Download, Share2, Check, ExternalLink } from 'lucide-react';
import TaxInvoiceSheet, { TaxInvoiceData } from './TaxInvoiceSheet';

interface InvoicePreviewModalProps {
  isOpen: boolean;
  onClose: () => void;
  invoiceData: TaxInvoiceData | null;
}

export const InvoicePreviewModal: React.FC<InvoicePreviewModalProps> = ({
  isOpen,
  onClose,
  invoiceData,
}) => {
  const [copied, setCopied] = useState(false);

  if (!isOpen || !invoiceData) return null;

  const handlePrint = () => {
    window.print();
  };

  const handleDownloadPdf = () => {
    // Standard web way to save invoice as PDF is triggering the browser's PDF print pipeline
    window.print();
  };

  const handleShareWhatsApp = () => {
    const text = encodeURIComponent(
      `Hello ${invoiceData.customerName},\n\nYour Tax Invoice ${invoiceData.invoiceNumber} for ₹${invoiceData.total.toLocaleString('en-IN')} has been generated by Kumar Enterprises.\n\nStatus: ${(invoiceData.status || 'Paid').toUpperCase()}\nBalance Due: ₹${(invoiceData.balance ?? 0).toLocaleString('en-IN')}\n\nThank you for doing business with us!`
    );
    const phoneClean = (invoiceData.customerPhone || '').replace(/\D/g, '');
    const waUrl = phoneClean
      ? `https://wa.me/${phoneClean}?text=${text}`
      : `https://wa.me/?text=${text}`;
    window.open(waUrl, '_blank');
  };

  const handleCopySummary = () => {
    const summary = `Invoice ${invoiceData.invoiceNumber} | Customer: ${invoiceData.customerName} | Amount: ₹${invoiceData.total.toLocaleString('en-IN')} | Status: ${invoiceData.status || 'Paid'}`;
    navigator.clipboard.writeText(summary);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="fixed inset-0 z-50 overflow-y-auto bg-slate-900/70 backdrop-blur-sm flex justify-center items-start p-2 sm:p-4 md:p-6 animate-fade-in">
      <div className="relative bg-slate-100 rounded-2xl shadow-2xl w-full max-w-5xl my-4 overflow-hidden border border-slate-200">
        {/* Modal Toolbar (hidden on print) */}
        <div className="bg-slate-900 text-white px-4 sm:px-6 py-3.5 flex items-center justify-between gap-3 flex-wrap print:hidden">
          <div className="flex items-center gap-2">
            <span className="font-bold text-sm sm:text-base">Tax Invoice Preview</span>
            <span className="font-mono text-xs text-primary-300 bg-primary-950/80 px-2.5 py-0.5 rounded border border-primary-800">
              {invoiceData.invoiceNumber}
            </span>
          </div>

          <div className="flex items-center gap-2 flex-wrap">
            <button
              onClick={handlePrint}
              className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-white/10 hover:bg-white/20 text-white text-xs font-semibold transition-colors"
            >
              <Printer className="w-3.5 h-3.5" />
              Print
            </button>
            <button
              onClick={handleDownloadPdf}
              className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-white/10 hover:bg-white/20 text-white text-xs font-semibold transition-colors"
            >
              <Download className="w-3.5 h-3.5" />
              Download PDF
            </button>
            <button
              onClick={handleShareWhatsApp}
              className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-semibold transition-colors"
            >
              <Share2 className="w-3.5 h-3.5" />
              WhatsApp
            </button>
            <button
              onClick={handleCopySummary}
              className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-white/10 hover:bg-white/20 text-white text-xs font-semibold transition-colors"
            >
              {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <ExternalLink className="w-3.5 h-3.5" />}
              {copied ? 'Copied' : 'Copy'}
            </button>
            <button
              onClick={onClose}
              className="p-1.5 rounded-lg text-slate-400 hover:text-white hover:bg-white/10 transition-colors ml-2"
              aria-label="Close Preview"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Modal Scrollable Body */}
        <div className="p-4 sm:p-6 md:p-8 max-h-[85vh] overflow-y-auto">
          <TaxInvoiceSheet data={invoiceData} />
        </div>
      </div>
    </div>
  );
};

export default InvoicePreviewModal;
