import React, { useState } from 'react';
import { useLocation, useNavigate, useParams } from 'react-router-dom';
import {
  ArrowLeft, Printer, Download, Share2, Check, ExternalLink,
  Edit3, FileText, CheckCircle2, ChevronRight
} from 'lucide-react';
import { useApp } from '../context/AppContext';
import TaxInvoiceSheet, { TaxInvoiceData } from '../components/invoice/TaxInvoiceSheet';
import { mockInvoices } from '../data/mockData';

export const InvoicePreviewPage: React.FC = () => {
  const location = useLocation();
  const navigate = useNavigate();
  const { id } = useParams<{ id: string }>();
  const { invoices } = useApp();
  const [copied, setCopied] = useState(false);

  // Priority 1: location.state (passed directly from Create Invoice or Billing page)
  // Priority 2: match from AppContext invoices by ID or invoiceNumber
  // Priority 3: match from mockInvoices
  // Priority 4: fallback sample invoice
  const passedData = location.state as TaxInvoiceData | undefined;

  const foundInvoice = id
    ? invoices.find(i => i.id === id || i.invoiceNumber === id) ||
      mockInvoices.find(i => i.id === id || i.invoiceNumber === id)
    : undefined;

  const rawInvoice = passedData || (foundInvoice ? {
    invoiceNumber: foundInvoice.invoiceNumber,
    invoiceDate: foundInvoice.date,
    dueDate: foundInvoice.dueDate,
    customerName: foundInvoice.customerName,
    customerPhone: foundInvoice.customerPhone,
    customerAddress: foundInvoice.customerAddress,
    customerGstin: foundInvoice.customerGstin,
    items: foundInvoice.items,
    subtotal: foundInvoice.subtotal,
    discount: foundInvoice.discount,
    gst: foundInvoice.gst,
    total: foundInvoice.total,
    paid: foundInvoice.paid,
    balance: foundInvoice.balance,
    status: foundInvoice.status,
    paymentMethod: foundInvoice.paymentMethod,
    notes: foundInvoice.notes,
  } : null);

  // Fallback to sample if opened directly with no parameters
  const invoiceData: TaxInvoiceData = rawInvoice || {
    invoiceNumber: 'INV-2026-0089',
    invoiceDate: new Date().toISOString().slice(0, 10),
    dueDate: new Date(Date.now() + 15 * 86400000).toISOString().slice(0, 10),
    customerName: 'Priya Sharma',
    customerPhone: '+91 99887 76655',
    customerAddress: '15 Park Street, Indiranagar, Bengaluru',
    customerGstin: '29BBBCP1234M1Z3',
    placeOfSupply: 'Karnataka (29)',
    items: [
      { productName: 'Office Chair Ergonomic Pro', hsnCode: '9401', quantity: 2, unitPrice: 12500, discount: 500, gstRate: 18, total: 28320 },
      { productName: 'Whiteboard 4x3 ft', hsnCode: '3924', quantity: 1, unitPrice: 2800, discount: 0, gstRate: 18, total: 3304 },
    ],
    subtotal: 27800,
    discount: 500,
    gst: 4824,
    total: 31624,
    paid: 31624,
    balance: 0,
    status: 'paid',
    paymentMethod: 'UPI',
    notes: 'Thank you for your business! Goods once sold are not returnable.',
  };

  const handlePrint = () => {
    window.print();
  };

  const handleDownloadPdf = () => {
    window.print();
  };

  const handleShareWhatsApp = () => {
    const text = encodeURIComponent(
      `Hello ${invoiceData.customerName},\n\nYour Tax Invoice ${invoiceData.invoiceNumber} for ₹${invoiceData.total.toLocaleString('en-IN')} has been generated by Kumar Enterprises.\n\nStatus: ${(invoiceData.status || 'Paid').toUpperCase()}\nBalance Due: ₹${(invoiceData.balance ?? 0).toLocaleString('en-IN')}\n\nThank you for doing business with us!`
    );
    const phoneClean = (invoiceData.customerPhone || '').replace(/\D/g, '');
    const waUrl = phoneClean
      ? `https://wa.me/${phoneClean}?text=${text}`
      : `https://wa.me/?text=${text}`;
    window.open(waUrl, '_blank');
  };

  const handleCopySummary = () => {
    const summary = `Invoice ${invoiceData.invoiceNumber} | Customer: ${invoiceData.customerName} | Amount: ₹${invoiceData.total.toLocaleString('en-IN')} | Status: ${invoiceData.status || 'Paid'}`;
    navigator.clipboard.writeText(summary);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="space-y-6 animate-fade-in print:p-0 print:m-0">
      {/* ── Top Bar (Hidden on print) ─────────────────────────────────── */}
      <div className="print:hidden flex items-center justify-between gap-4 flex-wrap">
        <div className="flex items-center gap-3">
          <button
            onClick={() => navigate(-1)}
            className="btn-secondary gap-1.5 py-2 px-3 text-slate-600 hover:text-slate-900"
          >
            <ArrowLeft className="w-4 h-4" />
            Back
          </button>
          <div>
            <div className="flex items-center gap-2 text-xs text-slate-400">
              <span className="cursor-pointer hover:text-slate-600" onClick={() => navigate('/billing')}>Billing</span>
              <ChevronRight className="w-3 h-3" />
              <span>Invoice Preview</span>
            </div>
            <h1 className="page-title text-xl">Tax Invoice {invoiceData.invoiceNumber}</h1>
          </div>
        </div>

        <div className="flex items-center gap-2 flex-wrap">
          <button
            onClick={handlePrint}
            className="btn-primary gap-1.5 shadow-md"
          >
            <Printer className="w-4 h-4" />
            Print Invoice
          </button>
          <button
            onClick={handleDownloadPdf}
            className="btn-secondary gap-1.5"
          >
            <Download className="w-4 h-4" />
            Download PDF
          </button>
          <button
            onClick={handleShareWhatsApp}
            className="inline-flex items-center justify-center gap-1.5 px-4 py-2.5 rounded-xl bg-emerald-600 hover:bg-emerald-500 text-white font-semibold text-sm shadow-sm transition-colors"
          >
            <Share2 className="w-4 h-4" />
            WhatsApp
          </button>
          <button
            onClick={handleCopySummary}
            className="btn-secondary gap-1.5"
            title="Copy summary"
          >
            {copied ? <Check className="w-4 h-4 text-emerald-500" /> : <ExternalLink className="w-4 h-4" />}
            {copied ? 'Copied' : 'Copy'}
          </button>
        </div>
      </div>

      {/* ── Printable Invoice Sheet ────────────────────────────────────── */}
      <div className="py-2">
        <TaxInvoiceSheet data={invoiceData} />
      </div>
    </div>
  );
};

export default InvoicePreviewPage;
